/*
 * Actions: [REDUCER_NAME]_[ACTION_NAME]
 */

export const APPBAR_CLOSE_LOGIN_MODAL = 'APPBAR_CLOSE_LOGIN_MODAL';
export const APPBAR_OPEN_LOGIN_MODAL = 'APPBAR_OPEN_LOGIN_MODAL';

export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';
export const DRAWER_CLOSE = 'DRAWER_TOGGLE';
export const DRAWER_TAB_CHANGE = 'DRAWER_TOGGLE';

export const HOME_SEARCH_DATE_CHANGE = 'HOME_SEARCH_DATE_CHANGE';

export const ROOM_OPEN_BOOKING_MODAL = 'ROOM_OPEN_BOOKING_MODAL';
export const ROOM_SELECTED_BOOKING_CHANGED = 'ROOM_SELECTED_BOOKING_CHANGED';
export const ROOM_SELECTED_VOUCHER_CHANGED = 'ROOM_SELECTED_VOUCHER_CHANGED';
export const ROOM_VOUCHER_IS_VALID = 'ROOM_VOUCHER_IS_VALID';
export const ROOM_CGU_ACCEPTED = 'ROOM_CGU_ACCEPTED';


export const BOOKING_OPEN_BOOKING_MODAL = 'ROOM_OPEN_BOOKING_MODAL';
export const BOOKING_SELECTED_BOOKING_CHANGED = 'ROOM_SELECTED_BOOKING_CHANGED';
export const BOOKING_SELECTED_VOUCHER_CHANGED = 'ROOM_SELECTED_VOUCHER_CHANGED';
export const BOOKING_VOUCHER_IS_VALID = 'ROOM_VOUCHER_IS_VALID';
export const BOOKING_CGU_ACCEPTED = 'ROOM_CGU_ACCEPTED';
export const BOOKING_SELECTED_CARD_CHANGED = 'BOOKING_SELECTED_CARD_CHANGED';
export const BOOKING_TOGGLE_AVAILABILITY = 'BOOKING_TOGGLE_AVAILABILITY';
export const BOOKING_RESET_AVAILABILITY = 'BOOKING_RESET_AVAILABILITY';
export const BOOKING_SELECTED_START_DATE_CHANGED = 'BOOKING_SELECTED_START_DATE_CHANGED';
export const BOOKING_SELECTED_END_DATE_CHANGED = 'BOOKING_SELECTED_END_DATE_CHANGED';
export const BOOKING_SELECTED_CAPACITY_CHANGED = 'BOOKING_SELECTED_CAPACITY_CHANGED';
export const BOOKING_ADD_TO_BOOKING_LIST = 'BOOKING_ADD_TO_BOOKING_LIST';
export const BOOKING_REMOVE_FROM_BOOKING_LIST = 'BOOKING_REMOVE_FROM_BOOKING_LIST';
export const BOOKING_UPDATE_BOOKING_LIST = 'BOOKING_UPDATE_BOOKING_LIST';
export const BOOKING_COMPLETE_LOADING = 'BOOKING_COMPLETE_LOADING';

export const PAYMENTS_OPEN_ADD_CARD_MODAL = 'PAYMENTS_OPEN_ADD_CARD_MODAL';
export const PAYMENTS_CLOSE_ADD_CARD_MODAL = 'PAYMENTS_CLOSE_ADD_CARD_MODAL';
export const PAYMENTS_LOADING_ADD_CARD = 'PAYMENTS_LOADING_ADD_CARD';

export const SNACKBAR_ERROR_OPEN = 'SNACKBAR_ERROR_OPEN';
export const SNACKBAR_ERROR_CLOSE = 'SNACKBAR_ERROR_CLOSE';
export const SNACKBAR_ERROR_MESSAGE_CHANGED = 'SNACKBAR_ERROR_MESSAGE_CHANGED';

export const NOTIFICATION_OPEN = 'NOTIFICATION_OPEN';
export const NOTIFICATION_OPEN_ERROR = 'NOTIFICATION_OPEN_ERROR';
export const NOTIFICATION_OPEN_WARNING = 'NOTIFICATION_OPEN_WARNING';
export const NOTIFICATION_OPEN_SUCCESS = 'NOTIFICATION_OPEN_SUCCESS';

export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';
export const NOTIFICATION_MESSAGE_CHANGED = 'NOTIFICATION_MESSAGE_CHANGED';

export const ADMIN_ROOM_SELECTED_CHANGED = 'ADMIN_ROOM_SELECTED_CHANGED';

export const ACCOUNTS_OPEN_FORGOT_PASSWORD_MODAL = 'ACCOUNTS_OPEN_FORGOT_PASSWORD_MODAL';
export const ACCOUNTS_CLOSE_FORGOT_PASSWORD_MODAL = 'ACCOUNTS_CLOSE_FORGOT_PASSWORD_MODAL';

export const NAVBAR_OPEN_MOBILE = 'NAVBAR_OPEN_MOBILE';
export const NAVBAR_CLOSE_MOBILE = 'NAVBAR_CLOSE_MOBILE';
export const NAVBAR_TOGGLE_MOBILE = 'NAVBAR_MOBILE_TOGGLE';

