/*
* Actions: [REDUCER_NAME]_[ACTION_NAME]
*/

export const APPBAR_CLOSE_LOGIN_MODAL = 'APPBAR_CLOSE_LOGIN_MODAL';
export const APPBAR_OPEN_LOGIN_MODAL = 'APPBAR_OPEN_LOGIN_MODAL';

export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';
export const DRAWER_CLOSE = 'DRAWER_TOGGLE';
export const DRAWER_TAB_CHANGE = 'DRAWER_TOGGLE';

export const HOME_SEARCH_DATE_CHANGE = 'HOME_SEARCH_DATE_CHANGE';

export const ROOM_OPEN_BOOKING_MODAL = 'ROOM_OPEN_BOOKING_MODAL';
export const ROOM_SELECTED_BOOKING_CHANGED = 'ROOM_SELECTED_BOOKING_CHANGED';
export const ROOM_SELECTED_VOUCHER_CHANGED = 'ROOM_SELECTED_VOUCHER_CHANGED';
export const ROOM_VOUCHER_IS_VALID = 'ROOM_VOUCHER_IS_VALID';

export const PAYMENTS_OPEN_ADD_CARD_MODAL = 'PAYMENTS_OPEN_ADD_CARD_MODAL';
export const PAYMENTS_CLOSE_ADD_CARD_MODAL = 'PAYMENTS_CLOSE_ADD_CARD_MODAL';